// #if UNITY_EDITOR
// using System;
// using System.Collections.Generic;
// using System.IO;
// using System.Text;
// using UnityEditor;
// using UnityEngine;
//
// namespace DataAssetsPackage.Editor
// {
//     /// <summary>
//     /// Simple writer to generate a partial class for DataAssets.
//     /// </summary>
//     public static class DataAssetPartialClassWriter
//     {
//         public static void Generate(List<Type> dataAssetSubclasses, string path)
//         {
//             if (dataAssetSubclasses.Count == 0)
//             {
//                 Debug.LogWarning("No subclasses of DataAsset found, creating an empty class anyways.");
//             }
//
//             StringBuilder sb = new StringBuilder();
//         
//             sb.AppendLine($"// Auto-generated by {nameof(DataAssetPartialClassWriter)}");
//             sb.AppendLine("using UnityEngine;");
//
//             List<string> namespaces = new List<string>();
//             foreach (Type subclass in dataAssetSubclasses)
//             {
//                 if (!string.IsNullOrEmpty(subclass.Namespace) && !namespaces.Contains(subclass.Namespace))
//                 {
//                     namespaces.Add(subclass.Namespace);
//                 }
//             }
//         
//             foreach (string ns in namespaces)
//             {
//                 sb.AppendLine($"using {ns};");
//             }
//         
//             sb.AppendLine();
//             sb.AppendLine("public partial class DataAssets");
//             sb.AppendLine("{");
//
//             foreach (Type subclass in dataAssetSubclasses)
//             {
//                 string propertyName = subclass.Name;
//                 string subclassName = subclass.Name;
//             
//                 propertyName = propertyName.Replace("DataAsset", string.Empty);
//             
//                 sb.AppendLine($"    public static {subclassName} {propertyName}() => Get<{subclassName}>();");
//             }
//
//             sb.AppendLine("}");
//
//             // Choose where to save the generated file
//             string filepath = Path.Combine(path, "DataAssets.Generated.cs");
//
//             if (!Directory.Exists(path))
//             {
//                 Directory.CreateDirectory(path);
//             }
//
//             File.WriteAllText(filepath, sb.ToString());
//             AssetDatabase.Refresh();
//
//             Debug.Log($"DataAssets partial class generated at: {filepath}");
//         }
//     }
// }
// #endif